
- name: Run docker graphite container
  become: true
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_graphite_env }}"
    expose: "{{ docker_graphite_expose }}"
    image: "{{ docker_graphite_image }}"
    name: "{{ docker_graphite_name }}"
    ports: "{{ docker_graphite_ports }}"
    links: "{{ docker_graphite_links }}"
    volumes: "{{ docker_graphite_volumes }}"
    memory_limit: "{{ docker_graphite_memory_limit }}"
    log_driver: "{{ docker_graphite_log_driver }}"
    log_opt: "{{ docker_graphite_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
  tags:
    - install
    - upgrade
